insert into private.actor (first_name, last_name, address, dob)
VALUES ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now()),
       ('firstName', 'LastName', 'address', now());

insert into private.film (launch_year, name)
VALUES (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName'),
       (now(), 'filmName');
